### ISSUE TITLE
The model cbharruin04.w3d cannot be opened.

### ISSUE THREAD

**Issue by MattTheLegoman** [OpenSAGE/OpenSAGE.BlenderPlugin#5]
The model cbharruin04.w3d cannot be opened.

```
Traceback (most recent call last):
  File "C:\Users\matt\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\io_mesh_w3d\__init__.py", line 143, in execute
    import_w3d.load(self, context, import_settings)
  File "C:\Users\matt\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\io_mesh_w3d\import_w3d.py", line 188, in load
    amtName = hierarchy.header.name
AttributeError: 'NoneType' object has no attribute 'header'

location: <unknown location>:-1
```

**Comment by Tarcontar** [comment]
should be fixed with ecdfc9abb6da00ed8ea31cf21ce0724f00369088
