### ISSUE TITLE
The model shell03brddur.w3d cannot be opened.

### ISSUE THREAD

**Issue by MattTheLegoman** [OpenSAGE/OpenSAGE.BlenderPlugin#6]
shell03brddur is BfME 1's shell map, a giant model of Barad-dur with a lightmap material and camera animation. I have just now tested other models with the similar materials like mmdbalin.w3d, yet they seem to work.

```
Traceback (most recent call last):
  File "C:\Users\matt\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\io_mesh_w3d\import_w3d.py", line 226, in load
    mesh_ob.parent = bpy.data.objects[parent_pivot.name]
KeyError: 'bpy_prop_collection[key]: key "AAA_BOX01" not found'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\matt\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\io_mesh_w3d\__init__.py", line 143, in execute
    import_w3d.load(self, context, import_settings)
  File "C:\Users\matt\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\io_mesh_w3d\import_w3d.py", line 228, in load
    mesh_ob.parent = bpy.data.objects[amtName]
KeyError: 'bpy_prop_collection[key]: key "SHELL03BRDDUR" not found'

location: <unknown location>:-1
```

**Comment by Tarcontar** [comment]
fixed with bbe4aea97af9d104aca30ada07cd6e23f17fc6f9
